### ISSUE TITLE
Начать программу с нуля

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/KSU.Visio#10]
Со старой программой у меня ничего не получилось, я зашёл в тупик, поэтому принял решение снести файлы, и создать новый проект, переосмыслить его.

**Comment by Parallusion** [comment]
Задание выполнено.

**Comment by YuriSilenok** [comment]
С чего вдруг вы решили что оно выполнено?
У Вас его ни кто не проверял

**Comment by Parallusion** [comment]
@YuriSilenok закрыл по двум причинам
1. Как мне кажется, проверка для удадения файлов из репозитория не нужна, собственно проверять то нечего, ибо кроме удаления старых классов и создания пустых новых ничего не было сделано.
2. Это решение я принял в связи с вашей звгруженностью, так как вы не проверяли мои таски и реквесты, то в связи с тем, что воемени у меня немного я решил не тормозить процесс и делать дальше.

**Comment by YuriSilenok** [comment]
7 августа в 20:56 вы создали запрос на слияние и в ту же минуту вы смержили с мастеров.
думаю вы вообще не дали мне шанса что-либо проверить

**Comment by Parallusion** [comment]
@YuriSilenok причиной этому служит вышеупомянутый 1 пункт, а также тот факт, что поднятая 5 августа задача, которую я вас попросил проверить в самом таске, не была проверена больше суток и в связи с этими причинами я закрыл таск

**Comment by YuriSilenok** [comment]
Ничего не понял, будем дальше работать.

**Comment by YuriSilenok** [comment]
еще мне кажется проблема того что Вы торопитесь в том, что дотянули до августа месяца

**Comment by Parallusion** [comment]
@YuriSilenok к сожалению, по семейным обстоятельствам время появилось только сейчас, и его все еще катастрофически мало, я понимаю как это все выглядит, но поделать с этим я ничего не мог.
