### ISSUE TITLE
Создать документацию пользователя

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/KSU.Visio#15]
[Документация пользователя](https://docs.google.com/document/d/1Jw3tUag3Kl87IDfl2CblPkByT7wEeaE7uK45U_4KxOY/edit?usp=sharing)

**Comment by Parallusion** [comment]
@YuriSilenok проверьте, пожалуйста документацию пользователя. Что нужно исправить?

**Comment by YuriSilenok** [comment]
Мне необходим доступ на комментирование
