### ISSUE TITLE
Создать классы и разработать их функционал

### ISSUE THREAD

**Issue by KudelinRoman** [Students-of-the-city-of-Kostroma/KSU.Visio#18]
[Диаграмма классов](https://www.draw.io/?state=%7B%22ids%22:%5B%2211fcUgZAXFcsWGCn_2LQqrRdZKTZM7RmI%22%5D,%22action%22:%22open%22,%22userId%22:%22107452487405623441224%22%7D#G11fcUgZAXFcsWGCn_2LQqrRdZKTZM7RmI)

**Comment by YuriSilenok** [comment]
назначите на меня, когда запрос на слияние будет завершен

**Comment by YuriSilenok** [comment]
Добрый день,

зачтено, смотрите журнал [здесь](https://docs.google.com/spreadsheets/d/1uBd4d3VvI4rYeuXkXmqLyEZSitS8K9pfVUDtM3i1Vg4/edit#gid=1293070679&range=L4)

Вам доступна оценка 3 за ТРПО КП

Спасибо,
Юрий
