### ISSUE TITLE
Реализовать методы перемещения фигур в пространстве (SelectFigure) и добавления текста (Text)

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/KSU.Visio#4]
План: #1

**Алгоритм поведения**
При двойном нажатии на объект открывается в правом нижнем углу текстовое поле, при заполнении которого - добавляется текст в сам объект. При нажатии на контур объекта, удерживая, перемещая объект - происходит перемещение объекта по области холста.

**Comment by YuriSilenok** [comment]
А закрыть таск?

**Comment by Parallusion** [comment]
К сожалению, я не успевал это сделать, приношу  свои извинения, до конца
дня закрою обязательно.

Спасибо.
Смирнов Илья.
17-ИСбо-2а

вт, 18 июн. 2019 г., 20:40 Юрий Силенок <notifications@github.com>:
