### ISSUE TITLE
Создать диаграмму классов с помощью draw.io

### ISSUE THREAD

**Issue by Parallusion** [Students-of-the-city-of-Kostroma/KSU.Visio#7]
[Ссылка на диаграмму классов](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=SeqDia.drawio#R7V1dc6O4Ev01qco8xIUQn4%2BOnWSzN7mbnczcye6LixjFZoLBi0nizK%2B%2FEiAMCLDsCOPUyjU1MULIoD7dfdRqiRM4WqyvImc5vw1d5J%2Boirs%2BgeMTVVV1FeI%2FpOQ9LQG6baUls8hzs7JNwb33C2WFSlb64rloVaoYh6Efe8ty4TQMAjSNS2VOFIVv5WpPoV%2F%2B1aUzQ0zB%2FdTx2dIfnhvP01JLNTflvyFvNqe%2FDAw7PbNwaOXsSVZzxw3fCkXw4gSOojCM02%2BL9Qj5pPdov6TXXTaczW8sQkHMc8Gj%2BeaNr797Zz%2Ff%2Frkf%2F%2B%2Fn9ePD97OslVfHf8ke%2BMYLUHbD8TvthdWbt%2FAdfAKeP4VBfJ%2BdAfjY8b1ZgL9P8W2gCBe8oij2cAcOsxNxuMSl07nnuzfOe%2FhCbnYVO9NnenQ%2BDyPvF27W8bM28ekozrCgGqUa9%2BRKXKzg0gitcJ072gOgUnTrrEsVb5xVnBVMQ993livvMX%2BMhRPNvOA8jONwkVViO5j2Fn5CtC4UZR1%2BhcIFiqN3XCU7q1vZJRn8LT09fNtACSoZPuZFGBlZoZPBd5Y3vZEw%2FpIJeQeBq4zAT1T8pMo98rH6IHeCApcRP37aOBFLFD6jUeiHWM7jIEzx4Pl%2BpYhCwkdPcSMgVktn6gWzm6TOWNuUfM26gRSF%2BNonP9Gauee6KCDCDGMndlLJETEtQy%2BIk27Sz%2FE%2F3HEjZaCf6PjGR%2FgYbI7xP1I9ikdhgJ%2FF8RK5IgyLN0SgUSPxVqXZDoNM7BjDXGLXtI6kDmukXpGx7yWyS2VMTR3YS8ALLCofbST6jQh8fAYYqUNW6rBGwr7ziPy7cOXFXkjaj9K6Fcn3JVxT4ROu1ZFstQaNHkfO22nilr3pCh9fRV9O4PA1xI0RPEKQ2jhS9TcvnsS4l7AcTu9Ip%2BIy%2BvfLI3a3zBX3c%2B8pZuvmPyANiFiMWZwYUzsCmc6ADHcBxsuLk%2Bik5Ati%2BMIZANScUMJsqHyi74wxmNJ38Oq1zi3vHYlBV77D%2BpjvkFZeKBqgxocGihrhcAAsT7zxntDEl2NCgTZe08smXgMmn9yB1ZWNB00kkkQDJj4KZuTGhqQZQvQqZPCOKNww%2B1I9mbSAB5WrrEpGFZ0oct6ZyhcuZqKpNyGVU%2BoprUwrl4TcANzR6RhdjUYByyYlpRAmXrvn8SgwPkYquhmQNv9AYm92%2BZWGC%2BTYtytA9z34BewQ6DKMFkBSIkGUCECoDBQVWoqtJ%2F9rJYKkc%2FIjU%2B%2BMHzUNlG7DlxWa3OGeWxUpS8VsfMMmYHKRCr65EilMTsd1p4fT1N2QCk76nbFOSQw%2FrXLpzV4i1FAFuZPM6pCq6ddqTYzwyQKbkJY7vm0%2F%2FW2d3Qt5%2FPNwzVQYI1%2FyPG67aXJr1Y48D%2BidET1bEr3u5JsPB%2FtienRmm7GKowg5McIWK4xOv6QqXsvCsnqr92CywBaUo%2B7Yw3KLp3Pe%2BpfhS%2BByV46cBeKod40F7QRTNFkt0dR7whAkAOG4MA%2BmcNXlqxauYt7n%2B4pNvxPMfJ52v6L4JeIWy1%2FPzi%2BOasQRtFYjQ4TUc7VWW2KO5YPJHVG20%2FDxJ%2FF62KigwMUeFhtgzMrJqYtXrHLDaEYGG4ijvcSZj8O3oL7N5DR%2Fm5H3ih85P136EeI5hfxIoc3vSxEtPr5gaheAycj3ps%2F1De7RBamDrx3WxV9aKERKVzgQMSW3GwZLb4phix7DdTvMcLNY3bc3m%2FaGKqQ30ragmJ5NnxOTKkGSytsT86yb9kQ%2Frya4PV1we4bg9kzB7VmC27NF41kR3aBoDQGiVQQItwkfVpKRejLE5E5p%2FiIHa6LJPGeUS6cJAeLpfE0yKGWXJEtWRrvERLtUA5bCW6rJOe%2FbXVKozA%2FkVu0d5H0kSR7qBzMEpakXi4fe0zxUNiyXhwYmlDNIYy8m28ME5ckMmvy5NSoLuhI%2FZP28tPbbVOXTWHuofszadzP9Ln2IWJTx%2BpDO5sQhSxmTeL90HKIcB5sKzivzroYJsIlIDumscyW7T2p9m9bDnTNheH0LZfziESAz9zoUr97zfC78YOaeVHfBeOAMCVIlFA%2BImsQ3MkcunbwoJ2%2Bp1kAveXlN410NoHTm55uy3UZhFNAcNunqd9H9zpK3YGeuXuZudSheo2dXrzWlbklX3w8eOF09je6IBwQbFKxPc5O%2BX5Tv14BW8f3A5E3Z7WwqUGsKH14TEQaOX1ieJynADjZB62zesLNdYzQ5LdyheHvfN0ZuHPMvMCK97xyjsSHDUhK%2F5BOC%2BIRV2WsO0oBTb2lFmtw6hl%2BzP93eMZrcPKZLS%2F%2F5do%2FR2IhRvrRLWnlBVt6mwVm6OF7t2cjrMpuIX6k%2FXTaR3hQOkEa%2BFzz0buR1ltP9mHsxmkQ0g1SaemEZQFi2ZUqvaAMLFj6cU4V2Z8a%2FiQOeRy%2BrbMew%2B9D33PRYmoP2DQM7myXsLCFIl7OEHYq374QgQ84SHpW68yYEdTZLSNcellaO5BtFSM8vyPProDzIg%2FSlIr2N8oy6yQJp59uV5NOM8oy6tF5p53vDQ%2B%2BjPIPNBN7spCTXgouz9LZWtvSq2vekjVE3pJOWvl1NPo%2BlrxuvSUvfGx56t%2FQmO8SjW4dKEy8mjGeUg3iAk8t3t9u%2FWTdlQ4wA0bnEABey%2Byr5O4kS0i5qrpbs%2Bp89Iak1JYpVX2u62Yl2yuxEK00Pp%2BnJ9fjzvAbArJtbkkxDkHj7fg2AWZc8Kiq9UOYWHoMF6X1jfpONSl2s4%2BRlM1Vh48IheR0wPnr0Q0IfznFRxi%2BAkR5eeuT3k%2F6fxwvKRNDaix8K3%2F8iVXDfp0djSjCSg3d6EODneygeFK4ih5vLkiN6XSPfWIUv0RS19AVdvItp0wy1yZkGh5FbevMxK%2BWCWPP1BhHyndh7RaV7q5Nr1hxVQsqF7Mq7j5ipyfQ5s8s28GBbMu0tLaUdwbSUAC1%2Fyg9gj42ZHR32BooJivgDuMDcgsDk6A5FHu4gwuXbYXncaLOsKvWGA83efExzX%2FDRCdV898Z8Kc%2Bh4MdG6I4PfkRmZfhBsfDbahXpjNmR47QyRISGOSjA1Lb2halShimk0%2FWHAimbLNQhSDEwDbUEVAXyIhVaVgWp%2Blak4qaqQBWMXprfc9zoNazqOkZNAULwqzO7I0AbHhbBbDS8SwSX0WuqvPDVy35ewb1v9A9f%2Bqqv44avblSMpCDjqymVSfxDG1821N%2Bp8VWgXYDvGXmhl82LX0uDOxOF7vGrfQqSq%2BlGmYtqgkhuPpanDcNDk1yrLlDdAbsdKIpVMr1QMzoZ3teB9gP0QOXEJw3494JP7LKr2xyooAokblACqA8AKMC71LIx0IvnqoGnBrgO0%2F0L8mpZ7K35kVSt%2BkiGnhVsNCBtVaw%2BcCzIF6APxHYrRkEhsIIYGp9CEF2yi0qROIKtZKTOcItVFm5dgf3pSiXdX4WVWV9eLVEtC49olPxTXhhM1E8pqckHtUS42T9oaA1b7XSstyHeypYIRxP1eChevvEKlgb2wf8HsM5LXLT%2BsK7qanVsR6MVu8JdUyt6U90Zr2uactBYHGYnJizgNbHWWwId7YBlw3QHjtIZvMa5R7zqtjZQ7CbiAQ1rUDC4irofkk26%2FRJFsmUPbFM9LJoPHLQDdsX4bol6tGPZZEaSmnpYMNOV%2B8cMZktT2sCsqgP4cTDbViW3lQxMTbAr7xCG68OG8gaqXsQ1P3uukAeowwMbY96J5D7xa7QZYxWPEYv4BXuG8IACyuYY6EavCD5sRK9kljnn%2FCph6O7SHejS%2Ba0o7TE0Z%2BltVtbSSoxhX5DmIKRrBDFhOARCl%2Fbv9lV8bf39n39cb3L788G8OT9j43Xklc8MOmUqcRFQO70TpJL1oum8u4WrSjN8eZOwamWuMjJv3QKgkrN3icWQYCSpSI6YKjE9u4ojL5gxaPr35vG16qDwRGBdQCJw7R3LbUa7Ey7NgDpAGnDtDct3Tx6TqvO%2BZFjEBgK1d3zgyK5lFyO7JFKm0YLtKUEgn7WgkYR8YuMg0xhtIj%2FuKWmrylI0PCArfOw9A71nhmIODHbmIl88i%2FULatVpD%2FHcN7qE2sX17z50r37M%2Fvv%2Bt%2F0aLmu478gJXh25K0ZXC%2BnOIK9zE7Jdfq3Qm8jvNBV9Qls3Xq5CbJ%2BShZZZrRsvWSDnExnSFZjGbOMMpBfcpnhHubF%2B7R1LwtudcA%2B4rX7tDTe%2BI9N1U7U%2BpdqtpF8aV7%2BlpyejuRPMkHtKX8ytrDDxwc4Bq5OqXLzi7htGM0Khm1u6QnHa2Mj3ps%2FI%2FSPAhflCufU7uTC3Ocyl1wuy4wccNtqx70vXiVHq7U7%2F9cvtEp%2Be0VTQJdAPuPruT%2FxQ51dr54%2F4%2BerVfzj7fm2gGsLTRuJdz1mEgftt7gUMd98Qe1UrU%2FlaElvDIw7Da4EKyhTEghViwZ%2FHpuhbmhJHV2ulV8dcREuvMJrSzOoCC7BXkkEha6cwsmufXuMFEce0A%2FUuxfFXsxs4DCrVyiq3M7A%2FKtVtTe2NSnwYhWFcrE78yW3oIlLj%2Fw%3D%3D)

**Comment by Parallusion** [comment]
Добрый вечер.

@YuriSilenok Проверьте пожалуйста диаграмму по ссылке в описании задачи.

Спасибо.
Смирнов Илья.
17-ИСбо-2а

**Comment by YuriSilenok** [comment]
Прошу Вас к вашей диаграмме приложить пояснительную записку

**Comment by YuriSilenok** [comment]
И если вы хотите что бы я проверял какие-либо задачи, их нужно перевешивать на меня

**Comment by Parallusion** [comment]
@YuriSilenok эта пояснительная записка будет только в качестве дополнения к диаграмме или в качестве задания из вашего списка "Пояснительная записка"?

**Comment by YuriSilenok** [comment]
пояснительная записка не является заданием, она поясняет диаграмму или другую наскальную живопись

**Comment by Parallusion** [comment]
@YuriSilenok достаточно ли мне будет указать как устроена иерархия классов, для чего нужны методы и как классы взаимосвязаны?

**Comment by YuriSilenok** [comment]
Да

**Comment by Parallusion** [comment]
@YuriSilenok 
[Ссылка на гугл документ](https://docs.google.com/document/d/1noP_i1DI59Iqa8fZsTiEKT4bbE0zRdFDagvODu0KFBM/edit?usp=sharing)

**Comment by Parallusion** [comment]
@YuriSilenok 
Проверьте, пожалуйста, [диаграмму классов](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=SeqDia.drawio#R7V1dc6O4Ev01qco8xIUQn4%2BOnWSzN7mbnczcye6LixjFZoLBi0nizK%2B%2FEiAMCLDsCOPUyjU1MULIoD7dfdRqiRM4WqyvImc5vw1d5J%2Boirs%2BgeMTVVV1FeI%2FpOQ9LQG6baUls8hzs7JNwb33C2WFSlb64rloVaoYh6Efe8ty4TQMAjSNS2VOFIVv5WpPoV%2F%2B1aUzQ0zB%2FdTx2dIfnhvP01JLNTflvyFvNqe%2FDAw7PbNwaOXsSVZzxw3fCkXw4gSOojCM02%2BL9Qj5pPdov6TXXTaczW8sQkHMc8Gj%2BeaNr797Zz%2Ff%2Frkf%2F%2B%2Fn9ePD97OslVfHf8ke%2BMYLUHbD8TvthdWbt%2FAdfAKeP4VBfJ%2BdAfjY8b1ZgL9P8W2gCBe8oij2cAcOsxNxuMSl07nnuzfOe%2FhCbnYVO9NnenQ%2BDyPvF27W8bM28ekozrCgGqUa9%2BRKXKzg0gitcJ072gOgUnTrrEsVb5xVnBVMQ993livvMX%2BMhRPNvOA8jONwkVViO5j2Fn5CtC4UZR1%2BhcIFiqN3XCU7q1vZJRn8LT09fNtACSoZPuZFGBlZoZPBd5Y3vZEw%2FpIJeQeBq4zAT1T8pMo98rH6IHeCApcRP37aOBFLFD6jUeiHWM7jIEzx4Pl%2BpYhCwkdPcSMgVktn6gWzm6TOWNuUfM26gRSF%2BNonP9Gauee6KCDCDGMndlLJETEtQy%2BIk27Sz%2FE%2F3HEjZaCf6PjGR%2FgYbI7xP1I9ikdhgJ%2FF8RK5IgyLN0SgUSPxVqXZDoNM7BjDXGLXtI6kDmukXpGx7yWyS2VMTR3YS8ALLCofbST6jQh8fAYYqUNW6rBGwr7ziPy7cOXFXkjaj9K6Fcn3JVxT4ROu1ZFstQaNHkfO22nilr3pCh9fRV9O4PA1xI0RPEKQ2jhS9TcvnsS4l7AcTu9Ip%2BIy%2BvfLI3a3zBX3c%2B8pZuvmPyANiFiMWZwYUzsCmc6ADHcBxsuLk%2Bik5Ati%2BMIZANScUMJsqHyi74wxmNJ38Oq1zi3vHYlBV77D%2BpjvkFZeKBqgxocGihrhcAAsT7zxntDEl2NCgTZe08smXgMmn9yB1ZWNB00kkkQDJj4KZuTGhqQZQvQqZPCOKNww%2B1I9mbSAB5WrrEpGFZ0oct6ZyhcuZqKpNyGVU%2BoprUwrl4TcANzR6RhdjUYByyYlpRAmXrvn8SgwPkYquhmQNv9AYm92%2BZWGC%2BTYtytA9z34BewQ6DKMFkBSIkGUCECoDBQVWoqtJ%2F9rJYKkc%2FIjU%2B%2BMHzUNlG7DlxWa3OGeWxUpS8VsfMMmYHKRCr65EilMTsd1p4fT1N2QCk76nbFOSQw%2FrXLpzV4i1FAFuZPM6pCq6ddqTYzwyQKbkJY7vm0%2F%2FW2d3Qt5%2FPNwzVQYI1%2FyPG67aXJr1Y48D%2BidET1bEr3u5JsPB%2FtienRmm7GKowg5McIWK4xOv6QqXsvCsnqr92CywBaUo%2B7Yw3KLp3Pe%2BpfhS%2BByV46cBeKod40F7QRTNFkt0dR7whAkAOG4MA%2BmcNXlqxauYt7n%2B4pNvxPMfJ52v6L4JeIWy1%2FPzi%2BOasQRtFYjQ4TUc7VWW2KO5YPJHVG20%2FDxJ%2FF62KigwMUeFhtgzMrJqYtXrHLDaEYGG4ijvcSZj8O3oL7N5DR%2Fm5H3ih85P136EeI5hfxIoc3vSxEtPr5gaheAycj3ps%2F1De7RBamDrx3WxV9aKERKVzgQMSW3GwZLb4phix7DdTvMcLNY3bc3m%2FaGKqQ30ragmJ5NnxOTKkGSytsT86yb9kQ%2Frya4PV1we4bg9kzB7VmC27NF41kR3aBoDQGiVQQItwkfVpKRejLE5E5p%2FiIHa6LJPGeUS6cJAeLpfE0yKGWXJEtWRrvERLtUA5bCW6rJOe%2FbXVKozA%2FkVu0d5H0kSR7qBzMEpakXi4fe0zxUNiyXhwYmlDNIYy8m28ME5ckMmvy5NSoLuhI%2FZP28tPbbVOXTWHuofszadzP9Ln2IWJTx%2BpDO5sQhSxmTeL90HKIcB5sKzivzroYJsIlIDumscyW7T2p9m9bDnTNheH0LZfziESAz9zoUr97zfC78YOaeVHfBeOAMCVIlFA%2BImsQ3MkcunbwoJ2%2Bp1kAveXlN410NoHTm55uy3UZhFNAcNunqd9H9zpK3YGeuXuZudSheo2dXrzWlbklX3w8eOF09je6IBwQbFKxPc5O%2BX5Tv14BW8f3A5E3Z7WwqUGsKH14TEQaOX1ieJynADjZB62zesLNdYzQ5LdyheHvfN0ZuHPMvMCK97xyjsSHDUhK%2F5BOC%2BIRV2WsO0oBTb2lFmtw6hl%2BzP93eMZrcPKZLS%2F%2F5do%2FR2IhRvrRLWnlBVt6mwVm6OF7t2cjrMpuIX6k%2FXTaR3hQOkEa%2BFzz0buR1ltP9mHsxmkQ0g1SaemEZQFi2ZUqvaAMLFj6cU4V2Z8a%2FiQOeRy%2BrbMew%2B9D33PRYmoP2DQM7myXsLCFIl7OEHYq374QgQ84SHpW68yYEdTZLSNcellaO5BtFSM8vyPProDzIg%2FSlIr2N8oy6yQJp59uV5NOM8oy6tF5p53vDQ%2B%2BjPIPNBN7spCTXgouz9LZWtvSq2vekjVE3pJOWvl1NPo%2BlrxuvSUvfGx56t%2FQmO8SjW4dKEy8mjGeUg3iAk8t3t9u%2FWTdlQ4wA0bnEABey%2Byr5O4kS0i5qrpbs%2Bp89Iak1JYpVX2u62Yl2yuxEK00Pp%2BnJ9fjzvAbArJtbkkxDkHj7fg2AWZc8Kiq9UOYWHoMF6X1jfpONSl2s4%2BRlM1Vh48IheR0wPnr0Q0IfznFRxi%2BAkR5eeuT3k%2F6fxwvKRNDaix8K3%2F8iVXDfp0djSjCSg3d6EODneygeFK4ih5vLkiN6XSPfWIUv0RS19AVdvItp0wy1yZkGh5FbevMxK%2BWCWPP1BhHyndh7RaV7q5Nr1hxVQsqF7Mq7j5ipyfQ5s8s28GBbMu0tLaUdwbSUAC1%2Fyg9gj42ZHR32BooJivgDuMDcgsDk6A5FHu4gwuXbYXncaLOsKvWGA83efExzX%2FDRCdV898Z8Kc%2Bh4MdG6I4PfkRmZfhBsfDbahXpjNmR47QyRISGOSjA1Lb2halShimk0%2FWHAimbLNQhSDEwDbUEVAXyIhVaVgWp%2Blak4qaqQBWMXprfc9zoNazqOkZNAULwqzO7I0AbHhbBbDS8SwSX0WuqvPDVy35ewb1v9A9f%2Bqqv44avblSMpCDjqymVSfxDG1821N%2Bp8VWgXYDvGXmhl82LX0uDOxOF7vGrfQqSq%2BlGmYtqgkhuPpanDcNDk1yrLlDdAbsdKIpVMr1QMzoZ3teB9gP0QOXEJw3494JP7LKr2xyooAokblACqA8AKMC71LIx0IvnqoGnBrgO0%2F0L8mpZ7K35kVSt%2BkiGnhVsNCBtVaw%2BcCzIF6APxHYrRkEhsIIYGp9CEF2yi0qROIKtZKTOcItVFm5dgf3pSiXdX4WVWV9eLVEtC49olPxTXhhM1E8pqckHtUS42T9oaA1b7XSstyHeypYIRxP1eChevvEKlgb2wf8HsM5LXLT%2BsK7qanVsR6MVu8JdUyt6U90Zr2uactBYHGYnJizgNbHWWwId7YBlw3QHjtIZvMa5R7zqtjZQ7CbiAQ1rUDC4irofkk26%2FRJFsmUPbFM9LJoPHLQDdsX4bol6tGPZZEaSmnpYMNOV%2B8cMZktT2sCsqgP4cTDbViW3lQxMTbAr7xCG68OG8gaqXsQ1P3uukAeowwMbY96J5D7xa7QZYxWPEYv4BXuG8IACyuYY6EavCD5sRK9kljnn%2FCph6O7SHejS%2Ba0o7TE0Z%2BltVtbSSoxhX5DmIKRrBDFhOARCl%2Fbv9lV8bf39n39cb3L788G8OT9j43Xklc8MOmUqcRFQO70TpJL1oum8u4WrSjN8eZOwamWuMjJv3QKgkrN3icWQYCSpSI6YKjE9u4ojL5gxaPr35vG16qDwRGBdQCJw7R3LbUa7Ey7NgDpAGnDtDct3Tx6TqvO%2BZFjEBgK1d3zgyK5lFyO7JFKm0YLtKUEgn7WgkYR8YuMg0xhtIj%2FuKWmrylI0PCArfOw9A71nhmIODHbmIl88i%2FULatVpD%2FHcN7qE2sX17z50r37M%2Fvv%2Bt%2F0aLmu478gJXh25K0ZXC%2BnOIK9zE7Jdfq3Qm8jvNBV9Qls3Xq5CbJ%2BShZZZrRsvWSDnExnSFZjGbOMMpBfcpnhHubF%2B7R1LwtudcA%2B4rX7tDTe%2BI9N1U7U%2BpdqtpF8aV7%2BlpyejuRPMkHtKX8ytrDDxwc4Bq5OqXLzi7htGM0Khm1u6QnHa2Mj3ps%2FI%2FSPAhflCufU7uTC3Ocyl1wuy4wccNtqx70vXiVHq7U7%2F9cvtEp%2Be0VTQJdAPuPruT%2FxQ51dr54%2F4%2BerVfzj7fm2gGsLTRuJdz1mEgftt7gUMd98Qe1UrU%2FlaElvDIw7Da4EKyhTEghViwZ%2FHpuhbmhJHV2ulV8dcREuvMJrSzOoCC7BXkkEha6cwsmufXuMFEce0A%2FUuxfFXsxs4DCrVyiq3M7A%2FKtVtTe2NSnwYhWFcrE78yW3oIlLj%2Fw%3D%3D). Что нужно доделать или исправить?

**Comment by YuriSilenok** [comment]
У меня нет возможность создать комментарий к элементу диаграммы
